[project]
name = "backend-portfolio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "alvin.mayore24@students.dkut.ac.ke" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn>=0.52.1",
]

[project.scripts]
backend-portfolio = "backend_portfolio:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
